import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "maureen",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  products: [
    {
      //_id: "1",
      name: "White Customised Shirt",
      slug: "white-customised-shirt",
      category: "Tops",
      image: "/images/Slider3.jpg",
      price: "900",
      countInStock: 10,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      //_id: "2",
      name: "Pastel Color Combination Hoodie",
      slug: "pastel-color-combination-hoodie",
      category: "Loungewear",
      image: "/images/Loungewear.jpg",
      price: "2500",
      countInStock: 5,
      brand: "Shien",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      //_id: "3",
      name: "Denim Dress",
      slug: "denim-dress",
      category: "Dresses",
      image: "/images/denimdress.jpg",
      price: "1000",
      countInStock: 100,
      brand: "zara",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      //_id: "4",
      name: "Rue Light Jacket",
      slug: "rue-light-jacket",
      category: "Jackets",
      image: "/images/ruejacket.jpg",
      price: "1100",
      countInStock: 20,
      brand: "Lorel",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      //_id: "5",
      name: "Light Blue Denim Pants ",
      slug: "light-blue-denim-pants",
      category: "Bottoms",
      image: "/images/denimpants.jpg",
      price: "1200",
      countInStock: 10,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      //_id: "6",
      name: "Aria Blouse ",
      slug: "aria-blouse",
      category: "Tops",
      image: "/images/ariablouse.jpg",
      price: "800",
      countInStock: 0,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
  ],
};
export default data;
