const data = {
  products: [
    {
      name: "White Customised Shirt",
      slug: "white-customised-shirt",
      category: "Tops",
      image: "/images/Slider3.jpg",
      price: "900",
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      name: "Pastel Color Combination Hoodie",
      slug: "pastel-color-combination-hoodie",
      category: "Loungewear",
      image: "/images/Loungewear.jpg",
      price: "2500",
      brand: "Shien",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      name: "Denim Dress",
      slug: "denim-dress",
      category: "Dresses",
      image: "/images/denimdress.jpg",
      price: "1000",
      brand: "zara",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      name: "Rue Light Jacket",
      slug: "rue-light-jacket",
      category: "Jackets",
      image: "/images/ruejacket.jpg",
      price: "1100",
      brand: "Lorel",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      name: "Light Blue Denim Pants ",
      slug: "light-blue-denim-pants",
      category: "Bottoms",
      image: "/images/denimpants.jpg",
      price: "1200",
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      name: "Aria Blouse ",
      slug: "aria-blouse",
      category: "Tops",
      image: "/images/ariablouse.jpg",
      price: "800",
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
  ],
};
export default data;
